services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  problem-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'SPRING_DATA_MONGODB_URI=mongodb://root:secret@mongodb:27017/mydatabase'
    ports:
      - '8080'
    depends_on:
      - 'mongodb'
    links:
      - 'mongodb'
    networks:
      - 'backend'
